spring.application.name=attendease

spring.datasource.url=jdbc:mysql://localhost:3306/attendease_db
spring.datasource.username=root
spring.datasource.password=mysql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
attendease.auth.username=admin
attendease.auth.password=admin123